spring:
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      jdbcUrl: jdbc:mariadb://172.20.0.21:3306/local_db?useUnicode=true&characterEncoding=utf8
      username: bnids
      password: qldps_2020
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 40
      maximumPoolSize: 40
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false

bnids-app:
  servers:
    localServer: 'http://localhost:12000/local/api/gateway'
    signage-interface-server: 'http://172.20.0.21/signage/api/signal/transit'
    gateControlServer: 'http://172.20.0.21/gate/api/gate'
    push-server: 'http://push.happyparking.co.kr'
    homenet-interface-server: 'http://172.20.0.21/homenet/api/transit'