server:
  port: 12010
  compression:
    enabled: true
    min-response-size: 256
  profiles:
    activate: dev
  servlet:
    context-path: gateway
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false

  jackson:
    serialization.write-dates-as-timestamps: false

  security:
    basic:
      enable: false
    ignored: /**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type: trace

bnids-app:
  servers:
    localServer: 'http://api.local.happyparking.co.kr/api/gateway'
    signage-interface-server: 'http://signage.local.happyparking.co.kr/api/signal/transit'
    gateControlServer: 'http://gate.local.happyparking.co.kr'
    push-server: 'http://push.happyparking.co.kr'
    homenet-interface-server: 'http://homenet.local.happyparking.co.kr'