spring:
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      url: jdbc:mariadb://db.local.happyparking.co.kr/local_db?useUnicode=true&characterEncoding=utf8
      username: bnids
      password: qlqp@2020e
      driver-class-name: org.mariadb.jdbc.Driver
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 40
      maximumPoolSize: 40
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false
