server:
  port: 12010
  compression:
    enabled: true
    min-response-size: 256

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:localdb
      driver-class-name: org.h2.Driver
      username: sa
      password:
      connectionTimeout: 30000
      idleTimeout: 300000
      maxLifetime: 1200000
      minimumIdle: 10
      maximumPoolSize: 15

  jpa:
    database: h2
    show-sql: true
    open-in-view: false
    generate-ddl: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

    h2:
      console:
        enabled: true
