server:
  port: 12010
  compression:
    enabled: true
    min-response-size: 256

spring:
  datasource:
    hikari: #https://github.com/brettwooldridge/HikariCP#configuration-knobs-baby
      jdbc-url: jdbc:mariadb://45.119.145.17/localdb?useUnicode=true&characterEncoding=utf8
      driver-class-name: org.mariadb.jdbc.Driver
      username: local
      password: fhzjf10@4
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      minimumIdle: 40
      maximumPoolSize: 40

  jpa:
    database: mysql
    show-sql: false
    open-in-view: false
    generate-ddl: false

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  h2:
    console:
      enabled: false

