server:
  port: 12010
  compression:
    enabled: true
    min-response-size: 256
  servlet:
    context-path: /gateway

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      use-new-id-generator-mappings: false

  jackson:
    serialization.write-dates-as-timestamps: false

  security:
    basic:
      enable: false
    ignored: /**

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: trace